import crypto from "crypto";
import fs from "fs";
import path from "path";

function loadEnvLocal(): string | undefined {
  const envPath = path.join(process.cwd(), ".env.local");
  if (!fs.existsSync(envPath)) return undefined;
  const content = fs.readFileSync(envPath, "utf-8");
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (trimmed.startsWith("ADMIN_PASSWORD=")) {
      return trimmed.slice("ADMIN_PASSWORD=".length).replace(/^["']|["']$/g, "");
    }
  }
  return undefined;
}

const password = process.env.ADMIN_PASSWORD || loadEnvLocal();

if (!password) {
  console.error("\n❌ ADMIN_PASSWORD is required for production build.");
  console.error("   Set ADMIN_PASSWORD as an environment variable or in .env.local.\n");
  process.exit(1);
}

const hash = crypto.createHash("sha256").update(password).digest("hex");
console.log(`Admin hash: generated (${hash.slice(0, 8)}...)`);

const output = `// Auto-generated by build-admin-hash.ts — do not edit
export const ADMIN_HASH: string = "${hash}";
`;
fs.writeFileSync(path.join(process.cwd(), "src/lib/admin-hash.generated.ts"), output, "utf-8");
